buildCommand: |
  pip install --no-cache-dir -r app/requirements.txt
services:
  - type: web
    name: lp-monitor-bot
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r app/requirements.txt
startCommand: |
  python app/main.py
    envVars:
      - key: DB_PATH
        value: /var/data/lp_monitor.db
      - key: BOT_TOKEN
        sync: false
      - key: ETH_RPC_URL
        sync: false
      - key: APTOS_RPC_URL
        sync: false
      - key: SUI_RPC_URL
        sync: false
      - key: PORT
        value: 8443
